name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64
    - name: cmake
      run: |
        mkdir build && cd build &&
        # Python bindings to be added after adding pybind11 install to CI
        cmake -DEMULATOR=0 -DPYTHON_BINDINGS=0 ../
    - name: make
      run: cd build && make
