name: build_host

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for gcc ${{ matrix.gcc-version }}, python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        gcc-version: ["10", "11", "12"]
        python-version: ["3.11"]
        # test on multiple python versions for a single os compiler combination
        include:
          - os: "ubuntu-latest"
            gcc-version: "12"
            python-version: "3.10"
    steps:
    - uses: actions/checkout@v4
    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pybind11
      run: pip install pybind11
    - name: cmake gcc-${{ matrix.gcc-version }}
      env:
       CC: gcc-${{ matrix.gcc-version }}
       CXX: g++-${{ matrix.gcc-version }}
      run: |
        $CXX --version
        mkdir build && cd build &&
        cmake -DPYTHON_BINDINGS=1 -Dpybind11_DIR=$(pybind11-config --cmakedir) ../
    - name: make
      run: cd build && make
