name: build_device_windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build device code with arduino-cli, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
    - name: Setup software
      run: choco install -y wget
    - uses: actions/checkout@v2
    - name: Setup arduino-cli
      run: |
        echo "$((Get-Item .).FullName)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip
        unzip -j arduino-cli_latest_Windows_64bit.zip
        echo $env:PATH
        pwd
        ls
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
        arduino-cli config set library.enable_unsafe_install true  # to enable --zip-path option of library installs
        arduino-cli core update-index
        arduino-cli core install STMicroelectronics:stm32
        arduino-cli version
    - name: Compile device code
      run: |
        cd device
        arduino-cli lib install --zip-path BLACKPILL_F401CC/PowerSensor/Libraries/Adafruit_BusIO.zip
        arduino-cli lib install --zip-path BLACKPILL_F401CC/PowerSensor/Libraries/Adafruit_GFX.zip
        arduino-cli lib install --zip-path BLACKPILL_F401CC/PowerSensor/Libraries/Adafruit_ST7735.zip
        make device
