name: build_device

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        arduino-cli config init > /dev/null
        arduino-cli core update-index > /dev/null
        arduino-cli version
