name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc-version: [9, 10]
    steps:
    - uses: actions/checkout@v3
    - name: cmake gcc-${{ matrix.gcc-version }}
      env:
       CC: gcc-${{ matrix.gcc-version }}
       CXX: g++-${{ matrix.gcc-version }}
      run: |
        mkdir build && cd build &&
        # Python bindings to be added after adding pybind11 install to CI
        cmake -DEMULATOR=1 -DPYTHON_BINDINGS=0 ../
    - name: make
      run: cd build && make
