name: build_device

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup arduino-cli
      run: |
        export PATH="$GITHUB_WORKSPACE/bin:$PATH"
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        arduino-cli config init > /dev/null
        arduino-cli core update-index > /dev/null
        arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
    - name: Compile device code
      run: |
        export PATH="$GITHUB_WORKSPACE/bin:$PATH"
        cd device && make device
