name: documentation

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sphinx and related dependencies
        run: sudo apt install -y doxygen && pip install -r docs/requirements.txt
      - name: Build documentation
        # run build twice to fix crossrefs
        run: make -C docs html && make -C docs html
      - uses: actions/upload-artifact@v4
        with:
          path: docs/_build/html/*
