name: documentation

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sphinx and related dependencies
        run: sudo apt install -y doxygen && pip install -r docs/requirements.txt
      - name: Build documentation
        # run build twice to fix crossrefs
        run: make -C docs html && make -C docs html
      - uses: actions/upload-artifact@v4
        with:
          path: docs/_build/html/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # deploy tags
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: docs/_build/html
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html

