name: doxygen

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mattnotmitt/doxygen-action@v1.9
        with:
          working-directory: 'docs'
      - uses: actions/upload-artifact@v3
        with:
          path: docs/build/*

  deploy:
    runs-on: ubuntu-latest
    needs: doxygen
    # deploy if on master branch or tag
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: docs/build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

